[template]
src = "bitcoin.conf.tmpl"
dest = "/etc/bitcoin.conf"
mode = "0600"
keys = [
  "rpcport",
  "rpcuser",
  "alerts",
  "alertnotify",
  "blocknotify",
  "checkblocks",
  "checklevel",
  "conf",
  "daemon",
  "datadir",
  "dbcache",
  "loadblock",
  "maxorphantx",
  "par",
  "pid",
  "prune",
  "reindex",
  "sysperms",
  "txindex",
  "addnode",
  "banscore",
  "bantime",
  "bind",
  "connect",
  "discover",
  "dns",
  "dnsseed",
  "externalip",
  "forcednsseed",
  "listen",
  "maxconnections",
  "maxreceivebuffer",
  "maxsendbuffer",
  "onion",
  "onlynet",
  "permitbaremultisig",
  "port",
  "proxy",
  "proxyrandomize",
  "seednode",
  "timeout",
  "whitebind",
  "whitelist",
  "disablewallet",
  "keypool",
  "paytxfee",
  "rescan",
  "salvagewallet",
  "sendfreetransactions",
  "spendzeroconfchange",
  "txconfirmtarget",
  "maxtxfee",
  "upgradewallet",
  "wallet",
  "walletbroadcast",
  "walletnotify",
  "zapwallettxes",
  "debug",
  "gen",
  "genproclimit",
  "help-debug",
  "logips",
  "logtimestamps",
  "minrelaytxfee",
  "printtoconsole",
  "shrinkdebugfile",
  "testnet",
  "datacarrier",
  "datacarriersize",
  "blockminsize",
  "blockmaxsize",
  "blockprioritysize",
  "server",
  "rest",
  "rpcbind",
  "rpcuser",
  "rpcpassword",
  "rpcport",
  "rpcallowip",
  "rpcthreads",
  "rpckeepalive",
  "rpcssl",
  "rpcsslcertificatechainfile",
  "rpcsslprivatekeyfile",
  "rpcsslciphers",
  "checkpoints",
  "dblogsize",
  "disablesafemode",
  "testsafemode",
  "dropmessagestest",
  "fuzzmessagestest",
  "flushwallet",
  "stopafterblockimport",
  "limitfreerelay",
  "relaypriority",
  "maxsigcachesize",
  "printpriority",
  "privdb",
  "regtest",
]
